--- #YAML:1.0
name:               Test-Debian
version:            0.01
abstract:           some tests for debian system
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://github.com/unera/test-debian-perl/issues
    homepage:    https://github.com/unera/test-debian-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
